# Use postgres/example user/password credentials
version: '3.9'

services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    container_name: postgres

  
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - postgres
    entrypoint: sh -c "npm i && npm run build && npm run dev"
    command: npm run dev
    restart: unless-stopped

  prisma-postgres-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prisma-postgres-api
    depends_on:
      - postgres
    ports:
      - "5555:5555"

    command: npx prisma studio
    entrypoint: sh -c "npx prisma generate && npx prisma db push && npx prisma db seed && npx prisma studio"
    restart: unless-stopped
  
volumes:
  postgres-data:

  
