# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./docker-data/db:/var/lib/postgresql/data 
    ports:
      - ${DB_PORT}:${DB_PORT}
  
