import './globals.css'
import { Providers } from './providers'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}
import dynamic from 'next/dynamic';

const DynamicNavbar = dynamic(() => import('@/components/ui/navbar'), { ssr: false });
export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (

    <html lang="en">

      <body className="pt-19">
        <DynamicNavbar />
        <Providers><div id="root">{children}</div></Providers>
      </body>
    </html>
  )
}